name: frontend-main-deploy

on:
  push:
    branches: [ dev, stage, master ]
    paths: 'frontend/main/**'
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: main
          release_branches: master
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
  deploy:
    needs: tag
    environment: ${GITHUB_REF##*/}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      # Deploy
      - name: Deploy ${GITHUB_REF##*/} to Vercel
        uses: amondnet/vercel-action@v19
        id: vercel-action-staging
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_MAIN_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_MAIN_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./frontend/main
